# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tracklab_system_monitor_pb2 as tracklab__system__monitor__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tracklab_system_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemMonitorServiceStub(object):
    """SystemMonitorService gRPC service.

    This service is used to collect system metrics from the host machine.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStats = channel.unary_unary(
                '/tracklab_internal.SystemMonitorService/GetStats',
                request_serializer=tracklab__system__monitor__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=tracklab__system__monitor__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/tracklab_internal.SystemMonitorService/GetMetadata',
                request_serializer=tracklab__system__monitor__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=tracklab__system__monitor__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.TearDown = channel.unary_unary(
                '/tracklab_internal.SystemMonitorService/TearDown',
                request_serializer=tracklab__system__monitor__pb2.TearDownRequest.SerializeToString,
                response_deserializer=tracklab__system__monitor__pb2.TearDownResponse.FromString,
                _registered_method=True)


class SystemMonitorServiceServicer(object):
    """SystemMonitorService gRPC service.

    This service is used to collect system metrics from the host machine.
    """

    def GetStats(self, request, context):
        """GetStats samples system metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """GetMetadata returns static metadata about the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TearDown(self, request, context):
        """TearDown instructs the system monitor to shut down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=tracklab__system__monitor__pb2.GetStatsRequest.FromString,
                    response_serializer=tracklab__system__monitor__pb2.GetStatsResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=tracklab__system__monitor__pb2.GetMetadataRequest.FromString,
                    response_serializer=tracklab__system__monitor__pb2.GetMetadataResponse.SerializeToString,
            ),
            'TearDown': grpc.unary_unary_rpc_method_handler(
                    servicer.TearDown,
                    request_deserializer=tracklab__system__monitor__pb2.TearDownRequest.FromString,
                    response_serializer=tracklab__system__monitor__pb2.TearDownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracklab_internal.SystemMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracklab_internal.SystemMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemMonitorService(object):
    """SystemMonitorService gRPC service.

    This service is used to collect system metrics from the host machine.
    """

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracklab_internal.SystemMonitorService/GetStats',
            tracklab__system__monitor__pb2.GetStatsRequest.SerializeToString,
            tracklab__system__monitor__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracklab_internal.SystemMonitorService/GetMetadata',
            tracklab__system__monitor__pb2.GetMetadataRequest.SerializeToString,
            tracklab__system__monitor__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TearDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracklab_internal.SystemMonitorService/TearDown',
            tracklab__system__monitor__pb2.TearDownRequest.SerializeToString,
            tracklab__system__monitor__pb2.TearDownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
