# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracklab_system_monitor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tracklab_system_monitor.proto'
)

_sym_db = _symbol_database.Default()


from . import tracklab_internal_pb2 as tracklab__internal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtracklab_system_monitor.proto\x12\x11tracklab_internal\x1a\x17tracklab_internal.proto\"6\n\x0fGetStatsRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x16\n\x0egpu_device_ids\x18\x02 \x03(\x05\"=\n\x10GetStatsResponse\x12)\n\x06record\x18\x01 \x01(\x0b\x32\x19.tracklab_internal.Record\"\x14\n\x12GetMetadataRequest\"@\n\x13GetMetadataResponse\x12)\n\x06record\x18\x01 \x01(\x0b\x32\x19.tracklab_internal.Record\"\x11\n\x0fTearDownRequest\"\x12\n\x10TearDownResponse2\xa4\x02\n\x14SystemMonitorService\x12U\n\x08GetStats\x12\".tracklab_internal.GetStatsRequest\x1a#.tracklab_internal.GetStatsResponse\"\x00\x12^\n\x0bGetMetadata\x12%.tracklab_internal.GetMetadataRequest\x1a&.tracklab_internal.GetMetadataResponse\"\x00\x12U\n\x08TearDown\x12\".tracklab_internal.TearDownRequest\x1a#.tracklab_internal.TearDownResponse\"\x00\x42\x1bZ\x19\x63ore/pkg/service_go_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracklab_system_monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031core/pkg/service_go_proto'
  _globals['_GETSTATSREQUEST']._serialized_start=77
  _globals['_GETSTATSREQUEST']._serialized_end=131
  _globals['_GETSTATSRESPONSE']._serialized_start=133
  _globals['_GETSTATSRESPONSE']._serialized_end=194
  _globals['_GETMETADATAREQUEST']._serialized_start=196
  _globals['_GETMETADATAREQUEST']._serialized_end=216
  _globals['_GETMETADATARESPONSE']._serialized_start=218
  _globals['_GETMETADATARESPONSE']._serialized_end=282
  _globals['_TEARDOWNREQUEST']._serialized_start=284
  _globals['_TEARDOWNREQUEST']._serialized_end=301
  _globals['_TEARDOWNRESPONSE']._serialized_start=303
  _globals['_TEARDOWNRESPONSE']._serialized_end=321
  _globals['_SYSTEMMONITORSERVICE']._serialized_start=324
  _globals['_SYSTEMMONITORSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
